export const PIPELINE_CATEGORIES = [
  { id: 'sales', label: 'Sales', icon: '💼', color: '#0052CC' },
  { id: 'fundraising', label: 'Fundraising', icon: '🏦', color: '#6554C0' },
  { id: 'recruiting', label: 'Recruiting', icon: '👥', color: '#00875A' },
  { id: 'partnerships', label: 'Partnerships', icon: '🤝', color: '#FF8B00' },
  { id: 'customer-success', label: 'Customer Success', icon: '🌟', color: '#00B8D9' },
  { id: 'non-traditional', label: 'Non-traditional', icon: '🎯', color: '#E11D48' },
]

export const PIPELINE_TEMPLATES = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // SALES (7)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'b2b-saas',
    name: 'B2B SaaS Sales',
    description: 'Standard pipeline for software-as-a-service companies selling to businesses',
    category: 'sales',
    icon: '💻',
    stages: [
      { name: 'lead', label: 'Lead', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'qualified', label: 'Qualified', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'demo', label: 'Demo', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 40, position: 2 },
      { name: 'trial', label: 'Free Trial', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 55, position: 3 },
      { name: 'proposal', label: 'Proposal', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'negotiation', label: 'Negotiation', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Won', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'TechStart Inc', deal_value: 24000, stage: 'demo', contact_name: 'Sarah Chen', notes: 'Interested in enterprise plan, 50 seats' },
      { company_name: 'CloudSync Labs', deal_value: 48000, stage: 'proposal', contact_name: 'Mike Johnson', notes: 'Annual contract, needs SSO integration' },
      { company_name: 'DataFlow Corp', deal_value: 12000, stage: 'lead', contact_name: 'Amy Park', notes: 'Inbound from blog post on automation' },
      { company_name: 'ScaleUp HQ', deal_value: 36000, stage: 'trial', contact_name: 'James Lee', notes: '14-day trial started, 20 users active' },
    ],
  },
  {
    id: 'outbound-prospecting',
    name: 'Outbound Prospecting',
    description: 'SDR-focused pipeline for cold outreach and lead qualification',
    category: 'sales',
    icon: '📞',
    stages: [
      { name: 'cold', label: 'Cold', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 5, position: 0 },
      { name: 'contacted', label: 'Contacted', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 15, position: 1 },
      { name: 'replied', label: 'Replied', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 30, position: 2 },
      { name: 'meeting-set', label: 'Meeting Set', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 50, position: 3 },
      { name: 'qualified', label: 'Qualified', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'handed-off', label: 'Handed to AE', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 90, position: 5 },
      { name: 'won', label: 'Converted', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Not Interested', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Meridian Systems', deal_value: 0, stage: 'contacted', contact_name: 'David Wright', notes: 'Email sequence #2 sent, LinkedIn connected' },
      { company_name: 'Apex Industries', deal_value: 0, stage: 'meeting-set', contact_name: 'Lisa Thompson', notes: 'Discovery call scheduled Thursday 2pm' },
      { company_name: 'NovaTech Solutions', deal_value: 0, stage: 'replied', contact_name: 'Chris Palmer', notes: 'Asked for more info, sent case study' },
    ],
  },
  {
    id: 'enterprise-sales',
    name: 'Enterprise Sales',
    description: 'Complex, multi-stakeholder deals with long sales cycles',
    category: 'sales',
    icon: '🏢',
    stages: [
      { name: 'discovery', label: 'Discovery', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'champion', label: 'Champion ID', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 20, position: 1 },
      { name: 'technical-eval', label: 'Technical Eval', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 35, position: 2 },
      { name: 'security-review', label: 'Security Review', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 50, position: 3 },
      { name: 'business-case', label: 'Business Case', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 65, position: 4 },
      { name: 'procurement', label: 'Procurement', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 80, position: 5 },
      { name: 'legal', label: 'Legal/Contract', color: '#00B8D9', bg_color: '#E6FCFF', border_color: '#79E2F2', probability: 90, position: 6 },
      { name: 'won', label: 'Closed Won', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 7, is_won: true },
      { name: 'lost', label: 'Closed Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 8, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Global Financial Corp', deal_value: 250000, stage: 'security-review', contact_name: 'Robert Kim', notes: 'SOC2 audit docs submitted, awaiting CISO approval' },
      { company_name: 'MegaRetail Inc', deal_value: 180000, stage: 'champion', contact_name: 'Patricia Nguyen', notes: 'VP Engineering is champion, building internal business case' },
      { company_name: 'Unified Health Systems', deal_value: 320000, stage: 'procurement', contact_name: 'Dr. Marcus Cole', notes: 'MSA redlines returned, final negotiation on SLA terms' },
    ],
  },
  {
    id: 'inbound-sales',
    name: 'Inbound Sales',
    description: 'For teams handling demo requests, trial signups, and website leads',
    category: 'sales',
    icon: '📥',
    stages: [
      { name: 'new-inquiry', label: 'New Inquiry', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'responded', label: 'Responded', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'needs-analysis', label: 'Needs Analysis', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 40, position: 2 },
      { name: 'solution', label: 'Solution Presented', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 60, position: 3 },
      { name: 'quote-sent', label: 'Quote Sent', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 75, position: 4 },
      { name: 'negotiation', label: 'Negotiation', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Won', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Bright Ideas Agency', deal_value: 8500, stage: 'needs-analysis', contact_name: 'Emily Roberts', notes: 'Requested demo via website, 15-person team' },
      { company_name: 'FastTrack Logistics', deal_value: 15000, stage: 'quote-sent', contact_name: 'Tom Anderson', notes: 'Sent annual pricing, following up Friday' },
      { company_name: 'GreenLeaf Organics', deal_value: 5200, stage: 'new-inquiry', contact_name: 'Rachel Green', notes: 'Filled out contact form, wants inventory solution' },
    ],
  },
  {
    id: 'ecommerce-wholesale',
    name: 'E-commerce Wholesale',
    description: 'B2B wholesale pipeline from inquiry to fulfillment and reorder',
    category: 'sales',
    icon: '📦',
    stages: [
      { name: 'inquiry', label: 'Inquiry', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'sample-sent', label: 'Sample Sent', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'pricing', label: 'Pricing', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'po-received', label: 'PO Received', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 70, position: 3 },
      { name: 'fulfilled', label: 'Fulfilled', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 90, position: 4 },
      { name: 'won', label: 'Reorder', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Urban Outfitters Buying', deal_value: 45000, stage: 'sample-sent', contact_name: 'Jennifer Walsh', notes: 'Sent 12 SKU samples, awaiting feedback' },
      { company_name: 'Whole Foods Regional', deal_value: 72000, stage: 'po-received', contact_name: 'Mark Stevens', notes: 'PO #4521 for Q2 inventory, ships March 15' },
      { company_name: 'Nordstrom Wholesale', deal_value: 120000, stage: 'pricing', contact_name: 'Diane Foster', notes: 'Negotiating MOQ and volume discount' },
    ],
  },
  {
    id: 'consulting-agency',
    name: 'Consulting / Agency',
    description: 'Professional services pipeline from lead to signed SOW',
    category: 'sales',
    icon: '💼',
    stages: [
      { name: 'lead', label: 'Lead', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'discovery', label: 'Discovery Call', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'scoping', label: 'Scoping', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 40, position: 2 },
      { name: 'proposal', label: 'Proposal Sent', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 60, position: 3 },
      { name: 'sow-signed', label: 'SOW Signed', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 85, position: 4 },
      { name: 'won', label: 'Kickoff', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'FinServ Group', deal_value: 85000, stage: 'scoping', contact_name: 'Alan Bradley', notes: 'Digital transformation, 3-month engagement' },
      { company_name: 'HealthNet Platform', deal_value: 42000, stage: 'proposal', contact_name: 'Sandra Liu', notes: 'UX redesign proposal sent, review meeting Tuesday' },
      { company_name: 'EduTech Solutions', deal_value: 28000, stage: 'discovery', contact_name: 'Kevin Morris', notes: 'Initial call scheduled, LMS migration project' },
    ],
  },
  {
    id: 'retail-local',
    name: 'Retail / Local Business',
    description: 'Simple pipeline for local businesses and retail sales',
    category: 'sales',
    icon: '🏪',
    stages: [
      { name: 'walk-in', label: 'Walk-in / Inquiry', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'follow-up', label: 'Follow-up', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 35, position: 1 },
      { name: 'quote', label: 'Quote Given', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 55, position: 2 },
      { name: 'negotiation', label: 'Negotiation', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 75, position: 3 },
      { name: 'won', label: 'Sold', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Johnson Family', deal_value: 3200, stage: 'quote', contact_name: 'Bill Johnson', notes: 'Kitchen renovation quote, deciding between two options' },
      { company_name: 'Martinez Wedding', deal_value: 8500, stage: 'follow-up', contact_name: 'Maria Martinez', notes: 'Catering for 150 guests, June date' },
      { company_name: 'Park Ave Dental', deal_value: 12000, stage: 'negotiation', contact_name: 'Dr. Sarah Park', notes: 'Office furniture package, wants 10% volume discount' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FUNDRAISING (4)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'vc-fundraising',
    name: 'VC Fundraising',
    description: 'Track venture capital fundraising from intro to wire',
    category: 'fundraising',
    icon: '🚀',
    stages: [
      { name: 'target', label: 'Target', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 5, position: 0 },
      { name: 'warm-intro', label: 'Warm Intro', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 15, position: 1 },
      { name: 'first-meeting', label: 'First Meeting', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 2 },
      { name: 'partner-meeting', label: 'Partner Meeting', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 45, position: 3 },
      { name: 'term-sheet', label: 'Term Sheet', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'due-diligence', label: 'Due Diligence', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Wired', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Passed', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Sequoia Capital', deal_value: 5000000, stage: 'first-meeting', contact_name: 'Partner: Alex Morgan', notes: 'Great first meeting, asked for metrics deck' },
      { company_name: 'a16z', deal_value: 5000000, stage: 'partner-meeting', contact_name: 'Partner: Ben Zhao', notes: 'Monday partner meeting, prep data room' },
      { company_name: 'Accel Partners', deal_value: 3000000, stage: 'warm-intro', contact_name: 'Via: CEO of PortCo', notes: 'Intro email sent, waiting for response' },
      { company_name: 'Index Ventures', deal_value: 5000000, stage: 'term-sheet', contact_name: 'Partner: Nina Shah', notes: 'Term sheet received, reviewing with lawyer' },
    ],
  },
  {
    id: 'angel-round',
    name: 'Angel Round',
    description: 'Early-stage angel investment pipeline',
    category: 'fundraising',
    icon: '😇',
    stages: [
      { name: 'identified', label: 'Identified', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'coffee-chat', label: 'Coffee Chat', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 25, position: 1 },
      { name: 'pitch', label: 'Pitched', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 40, position: 2 },
      { name: 'committed', label: 'Committed', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 3 },
      { name: 'docs-signed', label: 'Docs Signed', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 90, position: 4 },
      { name: 'won', label: 'Wired', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Passed', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Jason Calacanis', deal_value: 50000, stage: 'committed', contact_name: 'Jason C.', notes: 'Verbal yes for $50K, sending SAFE' },
      { company_name: 'Naval Ravikant', deal_value: 25000, stage: 'coffee-chat', contact_name: 'Naval R.', notes: 'Met at conference, follow-up coffee next week' },
      { company_name: 'Local Angel Group', deal_value: 100000, stage: 'pitch', contact_name: 'Group lead: Mark T.', notes: 'Presenting at Tuesday meeting, 8 angels attending' },
    ],
  },
  {
    id: 'grant-applications',
    name: 'Grant Applications',
    description: 'Track grant applications from research to award',
    category: 'fundraising',
    icon: '📋',
    stages: [
      { name: 'research', label: 'Researching', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 5, position: 0 },
      { name: 'drafting', label: 'Drafting', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 15, position: 1 },
      { name: 'submitted', label: 'Submitted', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 30, position: 2 },
      { name: 'review', label: 'Under Review', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 45, position: 3 },
      { name: 'interview', label: 'Interview', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 65, position: 4 },
      { name: 'won', label: 'Awarded', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Rejected', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'NSF SBIR Phase I', deal_value: 275000, stage: 'submitted', contact_name: 'Program Officer: Dr. Lee', notes: 'Application submitted Dec 5, results expected March' },
      { company_name: 'EU Horizon 2020', deal_value: 500000, stage: 'drafting', contact_name: 'Consortium Lead', notes: 'Draft due Jan 15, partner sections pending' },
      { company_name: 'Local Innovation Fund', deal_value: 50000, stage: 'interview', contact_name: 'Review Board', notes: 'Panel interview scheduled next Wednesday' },
    ],
  },
  {
    id: 'debt-loan',
    name: 'Debt / Loan',
    description: 'Track loan and credit applications through approval',
    category: 'fundraising',
    icon: '🏛️',
    stages: [
      { name: 'research', label: 'Research', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'application', label: 'Application', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'underwriting', label: 'Underwriting', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'approved', label: 'Approved', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 80, position: 3 },
      { name: 'won', label: 'Disbursed', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Denied', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'SVB Credit Line', deal_value: 500000, stage: 'underwriting', contact_name: 'Loan Officer: James Wu', notes: 'Financials submitted, 2-week review period' },
      { company_name: 'SBA 7(a) Loan', deal_value: 350000, stage: 'application', contact_name: 'Broker: Capital Access', notes: 'Application package being assembled' },
      { company_name: 'Revenue-Based Financing', deal_value: 200000, stage: 'approved', contact_name: 'Clearco Rep', notes: 'Approved for $200K, reviewing terms' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // RECRUITING (4)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'engineering-hiring',
    name: 'Engineering Hiring',
    description: 'Technical recruiting pipeline with coding assessments',
    category: 'recruiting',
    icon: '👨‍💻',
    stages: [
      { name: 'sourced', label: 'Sourced', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'recruiter-screen', label: 'Recruiter Screen', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 20, position: 1 },
      { name: 'technical', label: 'Technical Screen', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 35, position: 2 },
      { name: 'system-design', label: 'System Design', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 50, position: 3 },
      { name: 'onsite', label: 'Onsite / Final', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'offer', label: 'Offer', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Accepted', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Declined', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Senior Frontend Engineer', deal_value: 180000, stage: 'onsite', contact_name: 'Alex Rivera', notes: 'Strong React/TS skills, 6 YOE, onsite Thursday' },
      { company_name: 'Staff Backend Engineer', deal_value: 220000, stage: 'technical', contact_name: 'Priya Sharma', notes: 'Ex-Google, distributed systems, take-home sent' },
      { company_name: 'DevOps Engineer', deal_value: 160000, stage: 'offer', contact_name: 'Jordan Lee', notes: 'Offer sent $160K + equity, deciding by Friday' },
    ],
  },
  {
    id: 'general-hiring',
    name: 'General Hiring',
    description: 'Standard hiring pipeline for non-technical roles',
    category: 'recruiting',
    icon: '📋',
    stages: [
      { name: 'applied', label: 'Applied', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'resume-review', label: 'Resume Review', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 20, position: 1 },
      { name: 'phone-screen', label: 'Phone Screen', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 35, position: 2 },
      { name: 'interview', label: 'Interview', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 55, position: 3 },
      { name: 'reference', label: 'Reference Check', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 75, position: 4 },
      { name: 'offer', label: 'Offer', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 90, position: 5 },
      { name: 'won', label: 'Onboarded', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Rejected/Declined', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Marketing Manager', deal_value: 95000, stage: 'interview', contact_name: 'Taylor Brooks', notes: 'Second round with VP Marketing, strong portfolio' },
      { company_name: 'Sales Development Rep', deal_value: 65000, stage: 'phone-screen', contact_name: 'Casey Morgan', notes: 'Phone screen Monday, 2 years SDR experience' },
      { company_name: 'Office Manager', deal_value: 72000, stage: 'reference', contact_name: 'Robin Hayes', notes: 'References contacted, expecting replies this week' },
    ],
  },
  {
    id: 'executive-search',
    name: 'Executive Search',
    description: 'C-suite and VP-level executive hiring process',
    category: 'recruiting',
    icon: '👔',
    stages: [
      { name: 'identified', label: 'Identified', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 5, position: 0 },
      { name: 'outreach', label: 'Outreach', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 15, position: 1 },
      { name: 'exploratory', label: 'Exploratory', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 30, position: 2 },
      { name: 'panel', label: 'Panel Interview', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 50, position: 3 },
      { name: 'board-approval', label: 'Board Approval', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'offer', label: 'Offer & Negotiation', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Joined', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Passed', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'VP Engineering Search', deal_value: 300000, stage: 'panel', contact_name: 'Dr. Maria Santos', notes: 'Panel with CEO + CTO Thursday, strong systems background' },
      { company_name: 'CFO Search', deal_value: 350000, stage: 'exploratory', contact_name: 'Richard Keane', notes: 'Currently CFO at competitor, open to conversation' },
      { company_name: 'Head of Product', deal_value: 250000, stage: 'offer', contact_name: 'Yuki Tanaka', notes: 'Offer package sent: $250K + 1.5% equity' },
    ],
  },
  {
    id: 'internship-program',
    name: 'Internship Program',
    description: 'Pipeline for intern sourcing through onboarding',
    category: 'recruiting',
    icon: '🎓',
    stages: [
      { name: 'applied', label: 'Applied', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'screened', label: 'Screened', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'interview', label: 'Interview', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'project', label: 'Take-home Project', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 60, position: 3 },
      { name: 'offer', label: 'Offer', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 80, position: 4 },
      { name: 'won', label: 'Started', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Declined', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Summer Engineering Intern', deal_value: 0, stage: 'project', contact_name: 'Sam Chen (MIT)', notes: 'Take-home React project submitted, reviewing' },
      { company_name: 'Marketing Intern', deal_value: 0, stage: 'interview', contact_name: 'Alex Kim (Stanford)', notes: 'Strong social media portfolio, interview Friday' },
      { company_name: 'Data Science Intern', deal_value: 0, stage: 'offer', contact_name: 'Priya Patel (CMU)', notes: 'Offer sent, competing with Google internship' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PARTNERSHIPS (4)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'integration-partners',
    name: 'Integration Partners',
    description: 'Technical integration and API partnership pipeline',
    category: 'partnerships',
    icon: '🔌',
    stages: [
      { name: 'identified', label: 'Identified', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'outreach', label: 'Outreach', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 20, position: 1 },
      { name: 'alignment', label: 'Alignment Call', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 35, position: 2 },
      { name: 'technical', label: 'Technical Scoping', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 50, position: 3 },
      { name: 'build', label: 'Build', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 70, position: 4 },
      { name: 'qa', label: 'QA & Testing', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 85, position: 5 },
      { name: 'won', label: 'Live', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Cancelled', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Slack Integration', deal_value: 0, stage: 'build', contact_name: 'Slack Partner Team', notes: 'OAuth flow complete, building notification hooks' },
      { company_name: 'Salesforce Connector', deal_value: 0, stage: 'technical', contact_name: 'SF ISV team: Carlos', notes: 'Scoping bidirectional sync, API limits discussed' },
      { company_name: 'Stripe Billing Link', deal_value: 0, stage: 'alignment', contact_name: 'Stripe Partnerships', notes: 'Mutual interest, scheduling technical deep-dive' },
    ],
  },
  {
    id: 'channel-reseller',
    name: 'Channel / Reseller',
    description: 'Channel partner and reseller recruitment pipeline',
    category: 'partnerships',
    icon: '🏪',
    stages: [
      { name: 'prospecting', label: 'Prospecting', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'intro', label: 'Intro Meeting', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 25, position: 1 },
      { name: 'agreement', label: 'Agreement', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 45, position: 2 },
      { name: 'training', label: 'Training', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 65, position: 3 },
      { name: 'first-sale', label: 'First Sale', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 85, position: 4 },
      { name: 'won', label: 'Scaled', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Inactive', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'TechDistro EMEA', deal_value: 0, stage: 'training', contact_name: 'Hans Mueller', notes: 'Partner certification in progress, 3 reps enrolled' },
      { company_name: 'Pacific Solutions Group', deal_value: 0, stage: 'agreement', contact_name: 'Linda Tran', notes: 'Reviewing partner agreement terms, 20% margin' },
      { company_name: 'MidWest IT Services', deal_value: 0, stage: 'first-sale', contact_name: 'Bob Harrison', notes: 'First deal closed! $15K ARR, 2 more in pipeline' },
    ],
  },
  {
    id: 'co-marketing',
    name: 'Co-Marketing',
    description: 'Joint marketing campaigns and content partnerships',
    category: 'partnerships',
    icon: '📣',
    stages: [
      { name: 'idea', label: 'Idea', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'pitch', label: 'Pitch', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 30, position: 1 },
      { name: 'planning', label: 'Planning', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 50, position: 2 },
      { name: 'execution', label: 'Execution', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 75, position: 3 },
      { name: 'won', label: 'Results Review', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Cancelled', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Webinar with HubSpot', deal_value: 0, stage: 'planning', contact_name: 'HubSpot Co-Marketing', notes: 'Joint webinar on sales automation, March 20' },
      { company_name: 'Ebook with Stripe', deal_value: 0, stage: 'execution', contact_name: 'Stripe Content Team', notes: 'Writing in progress, design ready next week' },
      { company_name: 'Podcast Swap with Drift', deal_value: 0, stage: 'pitch', contact_name: 'Drift Marketing', notes: 'Proposed guest swap, awaiting confirmation' },
    ],
  },
  {
    id: 'affiliate-program',
    name: 'Affiliate Program',
    description: 'Affiliate and referral partner onboarding pipeline',
    category: 'partnerships',
    icon: '🔗',
    stages: [
      { name: 'applied', label: 'Applied', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'reviewed', label: 'Reviewed', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 35, position: 1 },
      { name: 'approved', label: 'Approved', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 55, position: 2 },
      { name: 'onboarding', label: 'Onboarding', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 70, position: 3 },
      { name: 'active', label: 'Active', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 85, position: 4 },
      { name: 'won', label: 'Top Performer', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Inactive', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'TechReviewer Blog', deal_value: 0, stage: 'active', contact_name: 'Sarah J.', notes: '12 referrals this month, $4800 commission earned' },
      { company_name: 'SaaS Weekly Newsletter', deal_value: 0, stage: 'onboarding', contact_name: 'Mike P.', notes: 'Approved, setting up tracking links and assets' },
      { company_name: 'YouTube Creator: DevOps Dan', deal_value: 0, stage: 'reviewed', contact_name: 'Dan K.', notes: '50K subscribers, reviewing content quality' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CUSTOMER SUCCESS (4)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'customer-onboarding',
    name: 'Customer Onboarding',
    description: 'New customer onboarding from signature to go-live',
    category: 'customer-success',
    icon: '🎯',
    stages: [
      { name: 'signed', label: 'Signed', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'kickoff', label: 'Kickoff', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 30, position: 1 },
      { name: 'setup', label: 'Setup & Config', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 50, position: 2 },
      { name: 'training', label: 'Training', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 70, position: 3 },
      { name: 'go-live', label: 'Go-Live', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 85, position: 4 },
      { name: 'won', label: '30-Day Check', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Churned Early', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Acme Corp Onboarding', deal_value: 48000, stage: 'setup', contact_name: 'John Davis', notes: 'SSO configured, importing 5000 contacts this week' },
      { company_name: 'Beta Industries', deal_value: 24000, stage: 'training', contact_name: 'Lisa Wang', notes: 'Admin training done, end-user sessions next week' },
      { company_name: 'Gamma Solutions', deal_value: 36000, stage: 'kickoff', contact_name: 'Peter Smith', notes: 'Kickoff call Thursday, sending welcome pack' },
    ],
  },
  {
    id: 'renewals',
    name: 'Renewals',
    description: 'Contract renewal pipeline with health scoring',
    category: 'customer-success',
    icon: '🔄',
    stages: [
      { name: '90-days', label: '90 Days Out', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 50, position: 0 },
      { name: 'health-check', label: 'Health Check', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 60, position: 1 },
      { name: 'proposal', label: 'Renewal Proposal', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 70, position: 2 },
      { name: 'negotiation', label: 'Negotiation', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 80, position: 3 },
      { name: 'won', label: 'Renewed', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Churned', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Acme Corp Renewal', deal_value: 48000, stage: 'health-check', contact_name: 'John Davis', notes: 'Health score: 85/100, usage up 30% YoY' },
      { company_name: 'TechGiant Renewal', deal_value: 120000, stage: 'negotiation', contact_name: 'VP Ops: Sandra', notes: 'Wants 15% multi-year discount, counter at 10%' },
      { company_name: 'StartupCo Renewal', deal_value: 12000, stage: '90-days', contact_name: 'Founder: Alex', notes: 'Low usage last quarter, scheduling QBR' },
    ],
  },
  {
    id: 'upsell-expansion',
    name: 'Upsell / Expansion',
    description: 'Expansion revenue from existing customers',
    category: 'customer-success',
    icon: '📈',
    stages: [
      { name: 'signal', label: 'Signal Detected', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'discovery', label: 'Discovery', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 30, position: 1 },
      { name: 'proposal', label: 'Proposal', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 55, position: 2 },
      { name: 'approved', label: 'Approved', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 80, position: 3 },
      { name: 'won', label: 'Expanded', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Not Now', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Acme Corp → Enterprise', deal_value: 36000, stage: 'proposal', contact_name: 'John Davis', notes: 'Upgrade from Pro to Enterprise, needs API access' },
      { company_name: 'Beta Industries +50 seats', deal_value: 18000, stage: 'signal', contact_name: 'Lisa Wang', notes: 'Hit 90% seat usage, likely needs expansion' },
      { company_name: 'Gamma Solutions Add-on', deal_value: 12000, stage: 'approved', contact_name: 'Peter Smith', notes: 'Analytics add-on approved, provisioning this week' },
    ],
  },
  {
    id: 'churn-prevention',
    name: 'Churn Prevention',
    description: 'At-risk customer intervention pipeline',
    category: 'customer-success',
    icon: '🛡️',
    stages: [
      { name: 'at-risk', label: 'At Risk', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 30, position: 0 },
      { name: 'outreach', label: 'Outreach', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 40, position: 1 },
      { name: 'recovery-plan', label: 'Recovery Plan', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 55, position: 2 },
      { name: 'executing', label: 'Executing', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 70, position: 3 },
      { name: 'won', label: 'Stabilized', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 4, is_won: true },
      { name: 'lost', label: 'Churned', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 5, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'DataCo (At Risk)', deal_value: 36000, stage: 'recovery-plan', contact_name: 'CTO: Mike Green', notes: 'Low adoption — offering free training + dedicated CSM' },
      { company_name: 'SmallBiz Corp', deal_value: 8400, stage: 'outreach', contact_name: 'Owner: Pat Lee', notes: 'No login in 30 days, calling to check in' },
      { company_name: 'MegaCorp Division', deal_value: 96000, stage: 'executing', contact_name: 'VP: Susan Park', notes: 'Custom integration built, usage recovering' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // NON-TRADITIONAL (7)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'real-estate',
    name: 'Real Estate',
    description: 'Property sales from lead to closing',
    category: 'non-traditional',
    icon: '🏠',
    stages: [
      { name: 'lead', label: 'Lead', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'viewing', label: 'Viewing', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'offer', label: 'Offer', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 40, position: 2 },
      { name: 'inspection', label: 'Inspection', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 60, position: 3 },
      { name: 'mortgage', label: 'Mortgage', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 75, position: 4 },
      { name: 'closing', label: 'Closing', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 90, position: 5 },
      { name: 'won', label: 'Handed Over', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Fell Through', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: '123 Oak Street', deal_value: 450000, stage: 'inspection', contact_name: 'Buyer: Smith Family', notes: 'Home inspection scheduled Wednesday, $450K offer accepted' },
      { company_name: '456 Maple Ave Condo', deal_value: 320000, stage: 'viewing', contact_name: 'Buyer: Jane Park', notes: 'Second showing tomorrow, very interested' },
      { company_name: '789 Lake House', deal_value: 680000, stage: 'mortgage', contact_name: 'Buyer: Williams', notes: 'Pre-approval received, final docs to lender' },
    ],
  },
  {
    id: 'freelancer-projects',
    name: 'Freelancer Projects',
    description: 'Freelance and contractor project pipeline',
    category: 'non-traditional',
    icon: '✏️',
    stages: [
      { name: 'inquiry', label: 'Inquiry', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'scoped', label: 'Scoped', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 30, position: 1 },
      { name: 'quoted', label: 'Quoted', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'accepted', label: 'Accepted', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 65, position: 3 },
      { name: 'in-progress', label: 'In Progress', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 80, position: 4 },
      { name: 'delivered', label: 'Delivered', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 90, position: 5 },
      { name: 'won', label: 'Paid', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Declined', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Logo Design - Bakery', deal_value: 1500, stage: 'in-progress', contact_name: 'Maria Garcia', notes: 'Round 2 revisions, presenting 3 concepts' },
      { company_name: 'Website Rebuild - Law Firm', deal_value: 8000, stage: 'quoted', contact_name: 'Attorney: Bob Clark', notes: 'Quote sent for 10-page site + blog, awaiting approval' },
      { company_name: 'Brand Package - Startup', deal_value: 4500, stage: 'delivered', contact_name: 'CEO: Tina Rogers', notes: 'Final files delivered, invoice sent net-30' },
    ],
  },
  {
    id: 'event-planning',
    name: 'Event Planning',
    description: 'Event management from inquiry to post-event',
    category: 'non-traditional',
    icon: '🎪',
    stages: [
      { name: 'inquiry', label: 'Inquiry', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'site-visit', label: 'Site Visit', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 30, position: 1 },
      { name: 'proposal', label: 'Proposal', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'booked', label: 'Booked', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 70, position: 3 },
      { name: 'planning', label: 'Planning', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 85, position: 4 },
      { name: 'won', label: 'Event Complete', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Cancelled', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Johnson Wedding (200 guests)', deal_value: 35000, stage: 'planning', contact_name: 'Sarah Johnson', notes: 'Venue confirmed, caterer booked, DJ pending' },
      { company_name: 'TechConf 2026', deal_value: 85000, stage: 'booked', contact_name: 'Organizer: Ryan', notes: 'Convention center reserved, sponsors confirmed' },
      { company_name: 'Corporate Holiday Party', deal_value: 15000, stage: 'proposal', contact_name: 'HR: Diana Wells', notes: 'Proposal for 300-person event, 3 venue options' },
    ],
  },
  {
    id: 'legal-law-firm',
    name: 'Legal / Law Firm',
    description: 'Legal case or client matter pipeline',
    category: 'non-traditional',
    icon: '⚖️',
    stages: [
      { name: 'consultation', label: 'Consultation', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 15, position: 0 },
      { name: 'engagement', label: 'Engagement', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 35, position: 1 },
      { name: 'discovery', label: 'Discovery', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 50, position: 2 },
      { name: 'filing', label: 'Filing', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 65, position: 3 },
      { name: 'hearing', label: 'Hearing', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 80, position: 4 },
      { name: 'won', label: 'Resolved', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 5, is_won: true },
      { name: 'lost', label: 'Closed/Lost', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 6, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Smith v. Corp LLC', deal_value: 25000, stage: 'discovery', contact_name: 'Client: John Smith', notes: 'Document production underway, deposition scheduled' },
      { company_name: 'Trademark Filing - TechBrand', deal_value: 5000, stage: 'filing', contact_name: 'CEO: Amy Chen', notes: 'USPTO application filed, 6-month review period' },
      { company_name: 'Estate Planning - Williams', deal_value: 8000, stage: 'engagement', contact_name: 'Client: Robert Williams', notes: 'Retainer signed, gathering asset documentation' },
    ],
  },
  {
    id: 'startup-accelerator',
    name: 'Startup Accelerator',
    description: 'Accelerator application and cohort pipeline',
    category: 'non-traditional',
    icon: '⚡',
    stages: [
      { name: 'scouting', label: 'Scouting', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 5, position: 0 },
      { name: 'applied', label: 'Applied', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 15, position: 1 },
      { name: 'screened', label: 'Screened', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 30, position: 2 },
      { name: 'interview', label: 'Interview', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 50, position: 3 },
      { name: 'selected', label: 'Selected', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 75, position: 4 },
      { name: 'cohort', label: 'In Cohort', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 90, position: 5 },
      { name: 'won', label: 'Demo Day', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Not Selected', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Y Combinator W26', deal_value: 500000, stage: 'interview', contact_name: 'Group Partner: TBD', notes: 'Interview batch 3, preparing 10-min pitch' },
      { company_name: 'Techstars NYC', deal_value: 120000, stage: 'applied', contact_name: 'MD: Sarah Kim', notes: 'Application submitted, video pitch recorded' },
      { company_name: '500 Global Batch 32', deal_value: 150000, stage: 'screened', contact_name: 'Reviewer', notes: 'Passed initial screen, awaiting interview slot' },
    ],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Product development and launch pipeline',
    category: 'non-traditional',
    icon: '🚀',
    stages: [
      { name: 'ideation', label: 'Ideation', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'research', label: 'Research', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 20, position: 1 },
      { name: 'mvp', label: 'MVP', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 40, position: 2 },
      { name: 'beta', label: 'Beta', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 60, position: 3 },
      { name: 'feedback', label: 'Feedback', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 75, position: 4 },
      { name: 'launch', label: 'Launch', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 90, position: 5 },
      { name: 'won', label: 'Post-Launch', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Shelved', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'AI Assistant Feature', deal_value: 0, stage: 'beta', contact_name: 'PM: Kevin Liu', notes: '50 beta users, NPS: 72, fixing top 3 bugs' },
      { company_name: 'Mobile App v2', deal_value: 0, stage: 'mvp', contact_name: 'Lead Dev: Ana', notes: 'Core flows complete, internal testing next week' },
      { company_name: 'Analytics Dashboard', deal_value: 0, stage: 'launch', contact_name: 'PM: Rachel Green', notes: 'Launch blog post drafted, PH submission ready' },
    ],
  },
  {
    id: 'content-pipeline',
    name: 'Content Pipeline',
    description: 'Content production from idea to publication',
    category: 'non-traditional',
    icon: '📝',
    stages: [
      { name: 'idea', label: 'Idea', color: '#5E6C84', bg_color: '#F4F5F7', border_color: '#DFE1E6', probability: 10, position: 0 },
      { name: 'outline', label: 'Outline', color: '#0052CC', bg_color: '#DEEBFF', border_color: '#4C9AFF', probability: 25, position: 1 },
      { name: 'draft', label: 'Draft', color: '#6554C0', bg_color: '#EAE6FF', border_color: '#8777D9', probability: 45, position: 2 },
      { name: 'review', label: 'Review', color: '#FF8B00', bg_color: '#FFF4E5', border_color: '#FFE380', probability: 65, position: 3 },
      { name: 'edit', label: 'Final Edit', color: '#974F0C', bg_color: '#FFFAE6', border_color: '#FFE380', probability: 80, position: 4 },
      { name: 'scheduled', label: 'Scheduled', color: '#00875A', bg_color: '#E3FCEF', border_color: '#57D9A3', probability: 90, position: 5 },
      { name: 'won', label: 'Published', color: '#006644', bg_color: '#E3FCEF', border_color: '#36B37E', probability: 100, position: 6, is_won: true },
      { name: 'lost', label: 'Killed', color: '#BF2600', bg_color: '#FFEBE6', border_color: '#FF8F73', probability: 0, position: 7, is_lost: true },
    ],
    sampleDeals: [
      { company_name: 'Blog: "10 Sales Metrics"', deal_value: 0, stage: 'draft', contact_name: 'Writer: Emily B.', notes: 'First draft 2000 words, needs data visuals' },
      { company_name: 'Case Study: Acme Corp', deal_value: 0, stage: 'review', contact_name: 'Customer: John D.', notes: 'Customer approved quotes, design in progress' },
      { company_name: 'Video: Product Tour', deal_value: 0, stage: 'edit', contact_name: 'Video: Mike S.', notes: 'Rough cut done, adding captions and CTA' },
      { company_name: 'Whitepaper: AI in Sales', deal_value: 0, stage: 'outline', contact_name: 'Writer: Dr. Sarah', notes: 'Research complete, outlining 5 chapters' },
    ],
  },
]
